//===========================================================================
//
// Module:	LNCPPAPI.H
//
// Description:
//
//		C++ API application header file. This file includes all the required
//		API header files.
//
//===========================================================================
//
// Copyright (c) 1996 Lotus Development Corporation. All rights reserved.
// This software is subject to the Lotus Software Agreement, Restricted
// Rights for U.S. government users, and applicable export regulations.
//
//===========================================================================

#include "lnsessio.hpp"
#include "lnacl.hpp"

