//===========================================================================
//
// Module:		LNFILE.HPP
//
// Description:
//
//		Class library definitions for LNFile class.
//
//===========================================================================
//
// Copyright (c) 1997, 1998 Lotus Development Corporation. All rights reserved.
// This software is subject to the Lotus Software Agreement, Restricted
// Rights for U.S. government users, and applicable export regulations.
//
//===========================================================================

