//===========================================================================
//
// Module:	LNGLOBAL.H
//
// Description:
//
//		C++ API global definitions. Must be included by all programs that use
//		the C++ API.
//
//===========================================================================
//
// Copyright (c) 1996-1998 Lotus Development Corporation. All rights reserved.
// This software is subject to the Lotus Software Agreement, Restricted
// Rights for U.S. government users, and applicable export regulations.
//
//===========================================================================

#ifndef LNGLOBAL_H
#define LNGLOBAL_H


//-----	Include other C++ API header files.

#include "lnglosym.h"		// typedefs and constant symbols
#include "lncapi.h"			// necessary C API header files
#include "lnenums.h"		// enumerations and typedefs
#include "lnglodat.h"		// global data declarations
#include "lnclassi.h"		// class IDs
#include "lnfref.h"			// forward references
#include "lnglofun.h"		// global function declarations
#include "lnerrdef.h"		// error codes
#include "lnmacros.h"		// macros and inline functions
#include "lncommon.hpp"		// common class definitions
#include "lnstring.hpp"		// LNString class definition
#include "lndate.hpp"		// Date/time related class definitions

#endif	// LNGLOBAL_H

