//===========================================================================
//
// Module:  LNLCKBYT.HPP
//
// Description:
//
//  Class library definition for LNLockBytes and related classes.
//
//===========================================================================
//
// Copyright (c) 1998 Lotus Development Corporation. All rights reserved.
// This software is subject to the Lotus Software Agreement, Restricted
// Rights for U.S. government users, and applicable export regulations.
//
//===========================================================================

#ifndef LNLOCKBYTES_HPP
#define LNLOCKBYTES_HPP


#endif

//===========================================================================
//                             REVISION HISTORY
//===========================================================================
//
// Date			Who		Description
// --------		---		-----------
//
// 1/29/98		spb		Created.
//
//===========================================================================
