//===========================================================================
//
// Module:		LNLINKS.HPP
//
// Description:	Class library definition for LNLinks class.
//
//===========================================================================
//
// Copyright (c) 1997 Lotus Development Corporation. All rights reserved.
// This software is subject to the Lotus Software Agreement, Restricted
// Rights for U.S. government users, and applicable export regulations.
//
//===========================================================================

