//===========================================================================
//
// Module:  LNEXTFIL.HPP
//
// Description:
//
//  Class library definition for LNExtendableFile and related classes.
//
//===========================================================================
//
// Copyright (c) 1998 Lotus Development Corporation. All rights reserved.
// This software is subject to the Lotus Software Agreement, Restricted
// Rights for U.S. government users, and applicable export regulations.
//
//===========================================================================

#ifndef LNEXTENDABLEFILE_HPP
#define LNEXTENDABLEFILE_HPP



#endif

//===========================================================================
//                             REVISION HISTORY
//===========================================================================
//
// Date			Who		Description
// --------		---		-----------
// 4/2/98		spb		Added LNExtendableFile::GetFileSize().
//
// ------------	Build 52
//
// 1/22/98		spb		Created.
//
//===========================================================================
