//===========================================================================
//
// Module:  LNSTOELE.HPP
//
// Description:
//
//  Class library definition for LNStorageElement and LNStorageElementBody.
//
//===========================================================================
//
// Copyright (c) 1998 Lotus Development Corporation. All rights reserved.
// This software is subject to the Lotus Software Agreement, Restricted
// Rights for U.S. government users, and applicable export regulations.
//
//===========================================================================

#ifndef LNSTOELE_HPP
#define LNSTOELE_HPP



#endif

//===========================================================================
//                             REVISION HISTORY
//===========================================================================
//
// Date			Who		Description
// --------		---		-----------
//
// 2/18/98		spb		Created.
//
//===========================================================================
